const productos = [
{"codigo":"SF492","descripcion":"SOLENOIDE PARED ACURAT","precio":195,"stock":5,"categoria":"Solenoides"},
{"codigo":"A91020","descripcion":"ANTISULFATANTE CAJA CON 30 PZAS","precio":239.80,"stock":2,"categoria":"Accesorios"},
{"codigo":"CINTAC","descripcion":"CINTA PLASTICA COOPER X10","precio":101,"stock":2,"categoria":"Accesorios"},
{"codigo":"SPPS100","descripcion":"SWITCH 75 AMP ARROW SPPS100","precio":136,"stock":5,"categoria":"Switches"},
{"codigo":"SPPS200","descripcion":"SWITCH LUZ UNIVERSAL ARROW SPPS200","precio":12,"stock":5,"categoria":"Switches"},
{"codigo":"CVF49","descripcion":"CARBON MARCHA BOSCH VF49","precio":16,"stock":20,"categoria":"Carbones"},
{"codigo":"F552","descripcion":"FLASHER 552 WAGNER","precio":64,"stock":5,"categoria":"Flashers"},
{"codigo":"FD1211","descripcion":"FLASHER HD12 TRIDON STAN AUTOMOTIV FHD125","precio":61,"stock":5,"categoria":"Flashers"},
{"codigo":"P905855","descripcion":"PASTILLA IGNICION VW 2930000","precio":92,"stock":5,"categoria":"Ignicion"},
{"codigo":"P905865","descripcion":"PASTILLA IGNICION VW JETTA A3 905865 2930600","precio":5,"stock":5,"categoria":"Ignicion"},
{"codigo":"TZ38C","descripcion":"TERMINAL ZAPATA 3/8 COBRIZADA","precio":89,"stock":20,"categoria":"Terminales"},
{"codigo":"S82602","descripcion":"SWITCH 2 PASOS ARROW 82602","precio":68,"stock":5,"categoria":"Switches"},
{"codigo":"S82600","descripcion":"SWITCH 1 PASO ARROW S82600","precio":13,"stock":5,"categoria":"Switches"},
{"codigo":"EU9004","descripcion":"ENCHUFE UNIDAD FOCO 9004","precio":12,"stock":10,"categoria":"Enchufes"},
{"codigo":"EUVW","descripcion":"ENCHUFE UNIDAD FOCO H4 VW BUENO","precio":12,"stock":10,"categoria":"Enchufes"},
{"codigo":"T10P","descripcion":"TERMINAL BATERIA PLACA 4 TORNILLOS T01010","precio":33,"stock":10,"categoria":"Terminales"},
{"codigo":"T5L","descripcion":"TERMINAL BATERIA PLACA T5L","precio":17.50,"stock":10,"categoria":"Terminales"},
{"codigo":"JS2011","descripcion":"BOCINA CLAXON VW HELLA","precio":121,"stock":3,"categoria":"Bocinas"},
{"codigo":"01200","descripcion":"BOCINA CLAXON CARACOL SEGER DOBLE","precio":174,"stock":3,"categoria":"Bocinas"},
{"codigo":"F90071LED4C","descripcion":"FOCO 9007 LED 4 CARAS ITALIOTURBO JUEGO","precio":253,"stock":2,"categoria":"Focos"},
{"codigo":"F9005LED4C","descripcion":"FOCO 9005 LED 4 CARAS FOLHID9005-GLA","precio":220,"stock":2,"categoria":"Focos"},
{"codigo":"F9004LED4C","descripcion":"FOCO 9004 LED 4 CARAS ITALIOTURBO JUEGO FOLHID9004-GLA","precio":220,"stock":2,"categoria":"Focos"},
{"codigo":"FHDI7LED4C","descripcion":"FOCO H7 LED 4 CARAS ITALIOTURBO FOLHIDH7-GLA JUEGO","precio":220,"stock":2,"categoria":"Focos"},
{"codigo":"FH11LED4C","descripcion":"FOCO H11 LED 4 CARAS ITALIOTURBO FOLHID11-GLA JUEGO","precio":253,"stock":2,"categoria":"Focos"},
{"codigo":"FH4LLED4C","descripcion":"FOCO H4 LED 4 CARAS ITALIOTURBO JUEGO FOLHIDH4-GLA","precio":98,"stock":2,"categoria":"Focos"},
{"codigo":"BM70S82","descripcion":"BULBO MOTOVENT. VW CARIBE 82/68","precio":154,"stock":3,"categoria":"Bulbos"},
{"codigo":"BM740","descripcion":"BULBO MOTOVENT. GM CHEVY","precio":149,"stock":3,"categoria":"Bulbos"},
{"codigo":"BM71795","descripcion":"BULBO MOTOVENT. VW COMBI 95/102","precio":39,"stock":5,"categoria":"Bulbos"},
{"codigo":"BR109","descripcion":"BALERO RODILLO DELCO 130 AMP ECONOM","precio":176,"stock":5,"categoria":"Baleros"},
{"codigo":"M110881","descripcion":"MARCADOR ACEITE VEETHREE 10151","precio":386,"stock":2,"categoria":"Medidores"},
{"codigo":"M37011","descripcion":"MARCADOR TEMPERATURA VDO","precio":187,"stock":2,"categoria":"Medidores"},
{"codigo":"PYANQUI","descripcion":"PALANCA DIRECCIONAL YANQUI","precio":264,"stock":2,"categoria":"Palancas"},
{"codigo":"M4365900","descripcion":"MOTOR PLACA ELEVADOR NISSAN TSURU GS CARFAN TROMPO","precio":114,"stock":2,"categoria":"Motores"},
{"codigo":"PDFR1070","descripcion":"PORTA DIODO FORD FR1070","precio":132,"stock":2,"categoria":"Porta Diodos"},
{"codigo":"PDF01AUTOM","descripcion":"PORTA DIODO FORD FR192-PF01 AUTOMOTIVE P01925","precio":165,"stock":2,"categoria":"Porta Diodos"},
{"codigo":"PDIIHR778AUT","descripcion":"PORTA DIODO NISSAN HITACHI IHR 778 AUTOMOTIVE","precio":75,"stock":2,"categoria":"Porta Diodos"},
{"codigo":"PASCHEVY","descripcion":"PASTILLA IGNICION CHEVY 2 TIPOS PDE310Y","precio":396,"stock":3,"categoria":"Ignicion"},
{"codigo":"P70568","descripcion":"PALANCA DIRECCIONAL GROTE TIPO ORIGINAL CAMION ECO C ARNES","precio":317,"stock":1,"categoria":"Palancas"},
{"codigo":"RIH738TP","descripcion":"REGULADOR NISSAN RIH 738 HITACHI TOTAL PARTS ASSER","precio":223,"stock":2,"categoria":"Reguladores"},
{"codigo":"RIH744ASS","descripcion":"REGULADOR NISSAN RIH 744 HITACHI ASSER","precio":116,"stock":2,"categoria":"Reguladores"},
{"codigo":"RF784TR","descripcion":"REGULADOR FORD F784 NEGRO TRANSPO","precio":135,"stock":3,"categoria":"Reguladores"},
{"codigo":"RF794TP","descripcion":"REGULADOR FORD F794 TOTAL PARTS 41945","precio":114,"stock":3,"categoria":"Reguladores"},
{"codigo":"R3258804","descripcion":"REGULADOR GM DELCO D411 CUTLAS","precio":143,"stock":3,"categoria":"Reguladores"},
{"codigo":"RE140X","descripcion":"REGULADOR GM E-140XR","precio":114,"stock":5,"categoria":"Reguladores"},
{"codigo":"RE141XR","descripcion":"REGULADOR FORD E-141XR","precio":114,"stock":5,"categoria":"Reguladores"},
{"codigo":"RIB501","descripcion":"REGULADOR NISSAN TSURU CHUECO IB-501","precio":145,"stock":2,"categoria":"Reguladores"},
{"codigo":"RD702TP","descripcion":"REGULADOR GM RD702 TOTAL PARTS ASSER 41931","precio":126,"stock":5,"categoria":"Reguladores"},
{"codigo":"RLE5001","descripcion":"REGULADOR NISSAN BARCO BOSCH LE5001","precio":248,"stock":5,"categoria":"Reguladores"},
{"codigo":"S71025","descripcion":"SOLENOIDE UNIVERSAL ACURAT 71025","precio":182,"stock":5,"categoria":"Solenoides"},
{"codigo":"FH10","descripcion":"FOCO 3157 HELLA X CAJA DE 10","precio":116,"stock":2,"categoria":"Focos"},
{"codigo":"F7443AC","descripcion":"FOCO 7443 HELLA X CAJA DE 10","precio":157,"stock":2,"categoria":"Focos"},
{"codigo":"F9006SH","descripcion":"FOCO 9006 55 HELLA BAJA","precio":47,"stock":3,"categoria":"Focos"},
{"codigo":"F9005H","descripcion":"FOCO 9005 55 HELLA","precio":49,"stock":3,"categoria":"Focos"},
{"codigo":"FH13H","descripcion":"FOCO H13 55 HELLA","precio":156,"stock":2,"categoria":"Focos"},
{"codigo":"FH4H","descripcion":"FOCO H4 55 HELLA","precio":31,"stock":10,"categoria":"Focos"},
{"codigo":"F9007H","descripcion":"FOCO 9007 55 HELLA","precio":49,"stock":5,"categoria":"Focos"},
{"codigo":"F9004H","descripcion":"FOCO 9004 55 HELLA","precio":49,"stock":5,"categoria":"Focos"},
{"codigo":"F67H","descripcion":"FOCO 67 HELLA X CAJA DE 10","precio":33,"stock":5,"categoria":"Focos"},
{"codigo":"FH3H","descripcion":"FOCO H3 55 HELLA","precio":23,"stock":5,"categoria":"Focos"},
{"codigo":"FH7H","descripcion":"FOCO H7 55 HELLA","precio":43,"stock":5,"categoria":"Focos"},
{"codigo":"F158H","descripcion":"FOCO 158 HELLA X CAJA DE 10","precio":24,"stock":5,"categoria":"Focos"},
{"codigo":"F1034H","descripcion":"FOCO 1034 HELLA X CAJA DE 10","precio":35,"stock":5,"categoria":"Focos"},
{"codigo":"F1176H","descripcion":"FOCO 1176 HELLA X CAJA DE 10","precio":37,"stock":5,"categoria":"Focos"},
{"codigo":"F1141H","descripcion":"FOCO 1141 HELLA X CAJA DE 10","precio":35,"stock":5,"categoria":"Focos"},
{"codigo":"BENDIXZEN","descripcion":"BENDIX ZEN FORD MOTORCRAF 10 DIENTES -1224","precio":114,"stock":1,"categoria":"Bendix"},
{"codigo":"AUTOBSCH","descripcion":"AUTOMATICO USATECH FORD SISTEMA BOSCH SLDSS1750","precio":220,"stock":1,"categoria":"Automaticos"},
{"codigo":"PCALTER2","descripcion":"PORTA CARBON ALTER FORD 2 GENERACION","precio":24,"stock":1,"categoria":"Porta Carbones"},
{"codigo":"PCALTER39","descripcion":"PORTA CARBON ALTER CUTLAS 39106","precio":29,"stock":1,"categoria":"Porta Carbones"},
{"codigo":"PCALTERCAV","descripcion":"PORTA CARBON ALTER DELCO CAVALIER C/RETEN","precio":29,"stock":1,"categoria":"Porta Carbones"},
{"codigo":"PCALTERFGR","descripcion":"PORTA CARBON ALTER FORD MOTORC GRIS 39207","precio":26,"stock":1,"categoria":"Porta Carbones"},
{"codigo":"PCALTER21","descripcion":"PORTA CARBON ALTER DELCO 21SI","precio":35,"stock":1,"categoria":"Porta Carbones"},
{"codigo":"SWCUB","descripcion":"SWITCH LLAVE UNIVERSAL CUB","precio":121,"stock":1,"categoria":"Switches"},
{"codigo":"MODVW7","descripcion":"MODULO ENCENDIDO VW 7 PINS TEMIC","precio":231,"stock":1,"categoria":"Modulos"},
{"codigo":"AUTOGM","descripcion":"AUTOMATICO USATECH GM DELCO SUBURBAN","precio":206,"stock":1,"categoria":"Automaticos"},
{"codigo":"AUTONISS","descripcion":"AUTOMATICO USATECH NISSAN HITACHI SIN CABLE -1219","precio":215,"stock":1,"categoria":"Automaticos"},
{"codigo":"AUTOVW","descripcion":"AUTOMATICO TOTAL PARTS VW SEDAN 11840","precio":248,"stock":1,"categoria":"Automaticos"},
{"codigo":"AUTOFORD","descripcion":"AUTOMATICO USATECH FORD MOTORCRAF GUIA 66205","precio":330,"stock":1,"categoria":"Automaticos"},
{"codigo":"BGNI3","descripcion":"BOMBA GASOLINA BOSCH NISSAN TSURU III ESPECIAL","precio":253,"stock":1,"categoria":"Bombas"},
{"codigo":"BGTEC","descripcion":"BOMBA GASOLINA TECNOFUEL UNIVERSAL REDONDA REFORZADA","precio":35,"stock":1,"categoria":"Bombas"},
{"codigo":"BOT2P","descripcion":"BOTON 2 POLOS MARCHA REFORZADO","precio":0,"stock":1,"categoria":"Botones"}
];
